#Enchant Maximum Levels:
  MENDING: 1
  DURABILITY: 3
  VANISHING_CURSE: 1
  WATER_WORKER: 1
  PROTECTION_EXPLOSIONS: 5
  BINDING_CURSE: 1
  DEPTH_STRIDER: 3
  PROTECTION_FALL: 4
  PROTECTION_FIRE: 5
  SWIFT_SNEAK: 3
  FROST_WALKER: 2
  PROTECTION_PROJECTILE: 5
  PROTECTION_ENVIRONMENTAL: 5
  OXYGEN: 3
  SOUL_SPEED: 3
  THORNS: 3
  DAMAGE_ARTHROPODS: 5
  FIRE_ASPECT: 2
  LOOT_BONUS_MOBS: 3
  DAMAGE_ALL: 5
  DAMAGE_UNDEAD: 5
  SWEEPING_EDGE: 3
  CHANNELING: 1
  ARROW_FIRE: 1
  IMPALING: 4
  ARROW_INFINITE: 1
  LOYALTY: 5
  RIPTIDE: 3
  MULTISHOT: 1
  PIERCING: 4
  ARROW_DAMAGE: 5
  ARROW_KNOCKBACK: 2
  QUICK_CHARGE: 3
  DIG_SPEED: 5
  LOOT_BONUS_BLOCKS: 3
  LUCK: 3
  LURE: 3
  SILK_TOUCH: 1

#Allowed Items

#Mutual Exclusivity