#Enchant Maximum Levels:
  MENDING: 1
  DURABILITY: 3
  VANISHING_CURSE: 1
  WATER_WORKER: 1
  PROTECTION_EXPLOSIONS: 5
  BINDING_CURSE: 1
  DEPTH_STRIDER: 3
  PROTECTION_FALL: 4
  PROTECTION_FIRE: 5
  SWIFT_SNEAK: 3
  FROST_WALKER: 2
  PROTECTION_PROJECTILE: 5
  PROTECTION_ENVIRONMENTAL: 5
  OXYGEN: 3
  SOUL_SPEED: 3
  THORNS: 3
  DAMAGE_ARTHROPODS: 5
  FIRE_ASPECT: 2
  LOOT_BONUS_MOBS: 3
  DAMAGE_ALL: 5
  DAMAGE_UNDEAD: 5
  SWEEPING_EDGE: 3
  CHANNELING: 1
  ARROW_FIRE: 1
  IMPALING: 4
  ARROW_INFINITE: 1
  LOYALTY: 5
  RIPTIDE: 3
  MULTISHOT: 1
  PIERCING: 4
  ARROW_DAMAGE: 5
  ARROW_KNOCKBACK: 2
  QUICK_CHARGE: 3
  DIG_SPEED: 5
  LOOT_BONUS_BLOCKS: 3
  LUCK: 3
  LURE: 3
  SILK_TOUCH: 1

#Enchant Cost (per_level):
  MENDING_COST: 1
  DURABILITY_COST: 1
  VANISHING_CURSE_COST: 1
  WATER_WORKER_COST: 1
  PROTECTION_EXPLOSIONS_COST: 1
  BINDING_CURSE_COST: 1
  DEPTH_STRIDER_COST: 1
  PROTECTION_FALL_COST: 1
  PROTECTION_FIRE_COST: 1
  SWIFT_SNEAK_COST: 1
  FROST_WALKER_COST: 1
  PROTECTION_PROJECTILE_COST: 1
  PROTECTION_ENVIRONMENTAL_COST: 1
  OXYGEN_COST: 1
  SOUL_SPEED_COST: 1
  THORNS_COST: 1
  DAMAGE_ARTHROPODS_COST: 1
  FIRE_ASPECT_COST: 1
  LOOT_BONUS_MOBS_COST: 1
  DAMAGE_ALL_COST: 1
  DAMAGE_UNDEAD_COST: 1
  SWEEPING_EDGE_COST: 1
  CHANNELING_COST: 1
  ARROW_FIRE_COST: 1
  IMPALING_COST: 1
  ARROW_INFINITE_COST: 1
  LOYALTY_COST: 1
  RIPTIDE_COST: 1
  MULTISHOT_COST: 1
  PIERCING_COST: 1
  ARROW_DAMAGE_COST: 1
  ARROW_KNOCKBACK_COST: 1
  QUICK_CHARGE_COST: 1
  DIG_SPEED_COST: 1
  LOOT_BONUS_BLOCKS_COST: 1
  LUCK_COST: 1
  LURE_COST: 1
  SILK_TOUCH_COST: 1

#Anvil settings
  Maximum_Level_Cost: 255

#Allowed Enchants per Items
  Item_Category_Names:
    - "Helmets"
    - "Wings"
    - "Chestplates"
    - "Boots"
    - "Leggings"
    - "NonWeapon_Tools"
    - "Axes"
    - "Melee"
    - "Recurve_Ranged"
    - "Charged_Ranged"
    - "Miscellaneous"

#Mutual Exclusivity